Vagrant::Config.run do |config|
    # This Vagrantfile is auto-generated by `vagrant package` to contain
    # the MAC address of the box. Custom configuration should be placed in
    # the actual `Vagrantfile` in this box.
    config.vm.box = "lucid32"
    config.vm.forward_port("web", 8080, 8080)
    config.vm.base_mac = "0800274153F3"
    config.vm.provision :chef_solo, :cookbooks_path => "cookbooks", :run_list => "recipe[python]"
    #config.vm.boot_mode = :gui

    config.vm.provision :chef_solo do |chef|
        chef.add_recipe("vagrant_main")
    end
end

# Load include vagrant file if it exists after the auto-generated
# so it can override any of the settings
include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
